### ISSUE TITLE
cifar10 dataset broken URL

### ISSUE THREAD

**Issue by rzsh** [nicholas-leonard/dp#115]
the link to cifar10 dataset (http://data.neuflow.org/data/cifar10.t7.tgz) is broken

**Comment by rzsh** [comment]
here is a replacement for it: http://torch7.s3-website-us-east-1.amazonaws.com/data/cifar10.t7.tgz

**Comment by nicholas-leonard** [comment]
https://github.com/nicholas-leonard/dp/commit/69017914b42d45657f5dee9407558540c41848d0
Thanks for bringing this up.
