### ISSUE TITLE
Surround remaining print statements in conditionals.

### ISSUE THREAD

**Issue by apage2** [nicholas-leonard/dp#118]
There are a few classes that still have unconditional print statements. Obviously things are in active development. Would it be possible to add a parameter like *progress* to classes like feedback and loss?

**Comment by nicholas-leonard** [comment]
Yes. I will look into it this weekend. Let's keep this issue open until its done. Thanks.

**Comment by nicholas-leonard** [comment]
Made the changes. Now you can call `xp:verbose()` or `xp:silent()` to toggle the verbosity of the experiment (or any other object like Visitors, Propagators, etc). For example scripts, this can be toggled with the cmdline option `--silent`. Thanks for the suggestion @apage2 !

**Comment by apage2** [comment]
Thanks, that was fast.
