### ISSUE TITLE
 'threads.worker' does not exist

### ISSUE THREAD

**Issue by hujiewang** [nicholas-leonard/dp#128]
Received this error from dp/utils/threads.lua while testing the alexnet example.
Is 'threads.worker'  suppose to be 'threads.queue'?

**Comment by nicholas-leonard** [comment]
Oh yeah, the threads-ffi package just changed that. Could you submit a Pull Request?

**Comment by hujiewang** [comment]
After changing 'worker' to 'queue', I kept getting all kinds of errors. I noticed that dp.threads is really old compare to what's in threads-ffi, so I updated it while keeping isEmpty() function. Not sure if it's the right way to do it, need some feedback.

code:
https://github.com/hujiewang/dp/blob/ab7d7ccf94bfd2cbfe598c8baa64f7895510e5b9/utils/threads.lua
