### ISSUE TITLE
Compatible with itorch

### ISSUE THREAD

**Issue by chwangaa** [nicholas-leonard/dp#140]
Error encountered in itorch

when execute `` require 'dp' `` in itorch, The following error given:

``
[string "local f = function() return require 'dp'..."]:2: loop or previous error loading module 'dp'
stack traceback:
	[C]: in function 'f'
	[string "local f = function() return require 'dp'..."]:2: in main chunk
	[C]: in function 'xpcall'
	/home/tom/torch/install/share/lua/5.1/itorch/main.lua:177: in function </home/tom/torch/install/share/lua/5.1/itorch/main.lua:143>
	/home/tom/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/home/tom/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/home/tom/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/home/tom/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/home/tom/torch/install/share/lua/5.1/itorch/main.lua:344: in main chunk
	[C]: in function 'require'
	[string "arg={'/home/tom/.ipython/profile_torch/securi..."]:1: in main chunk

``

**Comment by nicholas-leonard** [comment]
Yeah we don't really support itorch yet. For one, I can't get itorch to work on my laptop.
