### ISSUE TITLE
dp/data/imagesource.lua still uses dp.Carry() which returns a nil value.

### ISSUE THREAD

**Issue by deepakjnath** [nicholas-leonard/dp#141]
Hi,

dp/data/imagesource.lua still uses dp.Carry() which returns a nil value.

Is this an issue?

Thanks,
Deepak

ome/deepakjnath/torch/install/bin/luajit: ...nath/torch/install/share/lua/5.1/dp/data/imagesource.lua:76: attempt to call field 'Carry' (a nil value)
stack traceback:
	...nath/torch/install/share/lua/5.1/dp/data/imagesource.lua:76: in function 'loadValid'
	...nath/torch/install/share/lua/5.1/dp/data/imagesource.lua:53: in function '__init'
	...e/deepakjnath/torch/install/share/lua/5.1/torch/init.lua:54: in function <...e/deepakjnath/torch/install/share/lua/5.1/torch/init.lua:50>
	[C]: in function 'ImageSource'
	dj-cnn-1v0.lua:173: in main chunk
	[C]: in function 'dofile'
	...nath/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670
Ninja>th dj-cnn-1v0.lua --dataset ImageSource --trainPath '../../data/train_class' --validPath '../../data/train_class' --sampleSize '3,250,250' --loadSize '3,256,256'

**Comment by nicholas-leonard** [comment]
Can you submit a Pull Request?

**Comment by nicholas-leonard** [comment]
fixed. Thanks.
