### ISSUE TITLE
I trying to load my data and convert it to torch7 format?

### ISSUE THREAD

**Issue by SalemAmeen** [nicholas-leonard/dp#142]
I am trying to run (notmnist.lua) then, after that I will load my data using this function but I kept receiving this error. Could you please tell where is the error or my mistake? and how I could make change to load my data using this code?

th -i notmnist.lua
/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/init.lua:65: while creating metatable dp.NotMnist: bad argument #1 (dp is an invalid module name)
stack traceback:
	[C]: in function 'newmetatable'
	/usr/local/share/lua/5.1/torch/init.lua:65: in function 'class'
	notmnist.lua:8: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x010fd450f0

**Comment by nicholas-leonard** [comment]
You need to require dp first.

```lua
th
> require 'dp'
> ds = dp.NotMnist()
```

**Comment by SalemAmeen** [comment]
@nicholas-leonard , many thanks
Graet, it works. Could you please tell me can I use this file to load images saved in my desk?

**Comment by nicholas-leonard** [comment]
If they are organized on disk the same way as the NotMnist dataset, then yes. All images must have the same size. You might need to change `dp.NotMnist._image_size` to have the same size as your images.

**Comment by SalemAmeen** [comment]
Many thanks for answering
My  Images size are 3x64x64 and saved in folders A to Z. The folders represent the class of images which are saved inside each folder.
Regards,

**Comment by SalemAmeen** [comment]
Many thanks for answering
I organize my data as same as Notmnist dataset, can you please tell me if I can change the size my data to colour images  dp.NotMnist._image_size = 3x64x64

Regards,

**Comment by nicholas-leonard** [comment]
```lua
dp.NotMnist._image_size = {3,64,64}
```
3 channels for RGB color, yup. 64 height, 64 width.

Nicholas Léonard
917-741-7570

**Comment by SalemAmeen** [comment]
Many thanks
