### ISSUE TITLE
Early stopping when accuracy reaches 1 consistently

### ISSUE THREAD

**Issue by eulerreich** [nicholas-leonard/dp#161]
Is it currently possible to do this? If not, any suggestions on how to implement it?

**Comment by nicholas-leonard** [comment]
What do you mean by when accuracy reaches 1? Do you mean when it reaches 100%? What about the current early-stopping doesn't work for you?

**Comment by eulerreich** [comment]
Yea when it reaches 100%. I want the experiment to stop only when accuracy reaches 100% (or stopped manually by me). Right now I can set the maxTries to 99999 but then it wouldn't stop at all when accuracy reaches 100%.

**Comment by nicholas-leonard** [comment]
did you use EarlyStopper argument `maximize = true` and this : https://github.com/nicholas-leonard/dp/blob/master/examples/convolutionneuralnetwork.lua#L228?

**Comment by eulerreich** [comment]
yea.

**Comment by nicholas-leonard** [comment]
Oh that is because you set maxTries to high. You should set it to something like 50 or 100. There is currently no way to tell it to stop when it reaches the maximum accuracy. You could however submit a Pull Request to modify EarlyStopper to have a maxima argument.

**Comment by eulerreich** [comment]
What I would like is something along the lines of some arguments
`stop_threshold=1-epsilon, stop_threshold_period=50` which would mean to
stop after reaching accuracy 1 - epsilon for 50 consecutive minibatches.

**Comment by nicholas-leonard** [comment]
Hmmm. In that case, setting maxTries = 50 will do the trick for you.

**Comment by eulerreich** [comment]
The thing is that I don't want the experiment to stop after 50 minibatches
without surpassing the previous max IF IT DOESN'T SURPASS THE THRESHOLD. It
may very well be that the experiment will never reach accuracy 1, in which
I want it to keep running until I stop it myself.

**Comment by nicholas-leonard** [comment]
Yeah I see what you mean.
