### ISSUE TITLE
textsource.lua tokenizes incorrectly at newline

### ISSUE THREAD

**Issue by kmnns** [nicholas-leonard/dp#168]
textsource.lua, l.90:

``` {.lua}
data = stringx.replace(data, '\n', '<eos>')
```

Data file contains:

```
A B C
A B C
A B C
```

Result: `self._classes` containing

``` {.bash}
{
  1 : "A"
  2 : "B"
  3 : "C<eos>A"
  4 : "C<eos>"
}
```

Suggestion: Wrap `<eos>` in spaces, like so:

``` {.lua}
data = stringx.replace(data, '\n', ' <eos> ')
```

New `self._classes`:

``` {.bash}
{
  1 : "A"
  2 : "B"
  3 : "C"
  4 : "<eos>"
}
```

**Comment by nicholas-leonard** [comment]
Yeah you need to add a space between `C` and `\n` as in the PennTreeBank dataset.

**Comment by kmnns** [comment]
It is not uncommon for text editors to trim trailing spaces at save, so this is somewhat a pitfall. The suggested fix should accommodate both PennTreeBank and custom TextSources.
