### ISSUE TITLE
Cannot find trained model

### ISSUE THREAD

**Issue by johnny5550822** [nicholas-leonard/dp#169]
I followed this post (http://torch.ch/blog/2015/09/21/rmva.html) and trained a RAM. The model was trained for 500 epochs. But I am not able to locate the trained model, where can I find it?

**Comment by nicholas-leonard** [comment]
Hi. It should be in /home/[username]/save/[modelid].dat

**Comment by johnny5550822** [comment]
ok, great! Thanks.
