### ISSUE TITLE
DataSource with inputs of different length

### ISSUE THREAD

**Issue by Pyrena** [nicholas-leonard/dp#170]
First of all I'd like to thank everyone who is answering questions on this repository.
Maybe someone could help me with my problem:

I'm working with time series data where each training example has a different number of time steps and a feature size of 16.
So one training example might be a tensor of size 20x16, while another one is a tensor of size 12x16 and so on.
Is there any way to build a DataSource with this kind of input? I've only seen examples where each input has the same size, e.g. images with a fixed resolution.

**Comment by nicholas-leonard** [comment]
@Pyrena Say you want to build a batch of 32 examples where the longest sequences as 30. You could create an 32 x 16 tensor. The smaller sequences would have zeros at the front. Then you could use the rnn package to model your data where you use the maskZero() method. It was just added via this PR https://github.com/Element-Research/rnn/pull/46 . You have to put the zero elements at the start of the shorter sequences. To make this work with nn.Sequencer, you can use nn.SplitTable. So your datasource would use dp.DataView as input.

**Comment by Pyrena** [comment]
I finally got enough time to test it and it seems to be working.
Thank you!

**Comment by nicholas-leonard** [comment]
@Pyrena Awesome!
