### ISSUE TITLE
Not obvious where the datafiles are stored

### ISSUE THREAD

**Issue by hughperkins** [nicholas-leonard/dp#175]
Not obvious where the datafiles are stored.

I looked for them in the current directory, and also looked for a subdirectory of current directory like `data`, but did not find (or actually, or one computer they were in the current directory, I dont know).  After some hacking around, found them in `~/data`.  But might be good to, eg when downloading, print the directory they are being downloaded to.

**Comment by nicholas-leonard** [comment]
@hughperkins Yeah you are right. I should also update the docs to mention this.
