### ISSUE TITLE
Fail to use TextSource.lua

### ISSUE THREAD

**Issue by johnny5550822** [nicholas-leonard/dp#177]
I tried to run "th recurrentlanguagemodel.lua --dataset TextSource --trainFile "~/dp-master/examples/ptb.test.txt" --validFile "~/dp-master/examples/ptb.test.txt" --testFile "~/dp-master/examples/ptb.test.txt"

But then it return nothing. It seems that the file path is not obtained correctly.

**Comment by johnny5550822** [comment]
I think that because in textsource.lua the file_name is nil even though I provide the path

function TextSource:createTextSet(file_name, which_set) 

line 61:
   if file_name == nil or file_name == '' then
      return
   end

**Comment by nicholas-leonard** [comment]
@johnny5550822 Yeah try it without the `~`.

**Comment by johnny5550822** [comment]
@nicholas-leonard Thanks! I figured that out as well.
