### ISSUE TITLE
Does dp support 'image caption' data format?

### ISSUE THREAD

**Issue by liuchang8am** [nicholas-leonard/dp#178]
Say, dataset with image-sentence pairs, where image can be represented as raw or CNN feature vector, sentences can be represented as a sequence of one-hot vectors or simply indexed numbers. Is it possible to fit this kind of data to the dp dataset format (dp.DataSource maybe) ? It's kindof like the multi-target task, but the targets has order.

btw, thanks for the great work!

**Comment by nicholas-leonard** [comment]
@liuchang8am You can do it with a dp.ImageView for input and dp.ClassView (index numbers) for output. But all your sentences will need to have the same length (to fit them in tensor).

**Comment by liuchang8am** [comment]
Thanks, it finally works. Yet the length confine is a little bit annoying, as the sentences are of variable length. But I think padding zeros can work it around.
