### ISSUE TITLE
Cannot repeat convolutionneuralnetwork.lua experiment when using same random_seed

### ISSUE THREAD

**Issue by ilija139** [nicholas-leonard/dp#180]
If I set `random_seed` at https://github.com/nicholas-leonard/dp/blob/master/examples/convolutionneuralnetwork.lua#L235 to some constant, I expect when I run `th convolutionneuralnetwork.lua` multiple times to get the same accuracies at each respective epoch. However this is not happening. 
Any idea why?

**Comment by nicholas-leonard** [comment]
@ilija139 Because it is reset after the model is created which is when the weights get initialized. Sorry about that.
