### ISSUE TITLE
Error running convolutionalneuralnetwork.lua example

### ISSUE THREAD

**Issue by jrbtaylor** [nicholas-leonard/dp#181]
Running the provided example I'm getting the following error:

.../Torch/install/share/lua/5.1/dp/utils/utils.lua:39: attempt to index global 'fs' (a nil value)
stack traceback:
	.../Torch/install/share/lua/5.1/dp/utils/utils.lua:39: in function 'do_with_cwd'
	.../Torch/install/share/lua/5.1/dp/utils/utils.lua:52: in function 'check_and_download_file'
	.../Torch/install/share/lua/5.1/dp/data/datasource.lua:319: in function 'getDataPath'
	.../Torch/install/share/lua/5.1/dp/data/mnist.lua:135: in function 'loadData'
	.../Torch/install/share/lua/5.1/dp/data/mnist.lua:74: in function 'loadTrainValid'
	.../Torch/install/share/lua/5.1/dp/data/mnist.lua:61: in function '__init'
	.../Torch/install/share/lua/5.1/torch/init.lua:91: in function <.../Torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'Mnist'
	convolutionalneuralnetwork.lua:87: in main chunk
	[C]: in function 'dofile'
	.../Torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670

I updated all dependencies (including Torch itself) and am still getting the error. Any tips?

**Comment by nbeckage** [comment]
I have the exact same error. I just filed a separate report about datasets not loading. but fundamentally it is the same issue

**Comment by jrbtaylor** [comment]
I fixed the issue by changing the utils.lua function dp.do_with_cwd as follows:
ls.cwd() was replaced with lfs.currentdir()
ls.chdir() was replaced with lfs.chdir()

I don't know what package ls is referring to, but lfs (Lua file system) seems to do what I assume those lines were meant for.

**Comment by nicholas-leonard** [comment]
@jrbtaylor Can you send a Pull Request?

**Comment by nicholas-leonard** [comment]
@jrbtaylor nevermind I just pushed the update. Thanks!
