### ISSUE TITLE
dataset load error

### ISSUE THREAD

**Issue by nbeckage** [nicholas-leonard/dp#182]
Hi,
I am completely new to using dp and have been training neural networks by writing my own functions. However, I cannot even get data loaded with the dp function.
Quick review of what I have done. I have used both luarocks and git clone to install the package.

I then run th and in torch I run require 'dp'. When I then run ds = dp.Mnist() I get this error.
...rs/nicole/torch/install/share/lua/5.1/dp/utils/utils.lua:39: attempt to index global 'fs' (a nil value)

Thanks for your help.
Nicole

**Comment by nicholas-leonard** [comment]
Fixed in latest commit. Thanks @nbeckage !
