### ISSUE TITLE
Running a recurrent language model with SoftMaxTree 

### ISSUE THREAD

**Issue by NorThanapon** [nicholas-leonard/dp#183]
The model without SoftMaxTree works fine. For example, ```lm:forward(torch.CudaTensor{131})``` gives me log-likelihood of the next word (at least that what I think). But when I tried playing around with a model that use SoftMaxTree, I couldn't make ```forward()``` works. A few issues I found:

1. I want to generate what could be the next word, so I don't have ```targets``` to feed along with the ```input```.
2. I trained a model in batch of 64, but in the application the batch size is just 1.

Is there any example that use a model from [recurrentlanguagemodel.lua](https://github.com/nicholas-leonard/dp/blob/master/examples/recurrentlanguagemodel.lua)? 

Thanks

**Comment by nicholas-leonard** [comment]
@NorThanapon 

 1. SoftMaxTree doesn't have any method for sampling next word. But it could be implemented if you had the time. You could sample from root to leaf.

 2. The batch size is how many examples are fed into the model. So feed more models to get more. For evaluation of a single long sequence, batchsize of 1 is best as the recursion can happen for the entire sequence. On the other hand, a batchsize of 2 or more for evaluation would split that sequence into smaller sequences.

**Comment by NorThanapon** [comment]
Thank you @nicholas-leonard. To confirm my understanding after looking around

There are 2-3 files involving SoftMaxTree

1. [SoftmaxTree.lua](https://github.com/clementfarabet/lua---nnx/blob/888c940fe953e12b7277f4b9b09761fc73818062/SoftMaxTree.lua): ```SoftMaxTree:updateOutput(inputTable)``` somehow has to return an overall distribution during application (not train or eval)
2. [SoftMaxTree.c](https://github.com/clementfarabet/lua---nnx/blob/888c940fe953e12b7277f4b9b09761fc73818062/generic/SoftMaxTree.c):  a new function similar to ```nn_(SoftMaxTree_updateOutput)(lua_State *L)```, but going from root to leaf nodes and returning a probability distribution.
3. [SoftMaxTree.cu](https://github.com/nicholas-leonard/cunnx/blob/master/SoftMaxTree.cu): similar to (2).

This is not an urgent issue for me right now. At some point I'll have to do it if it is still not available. You can close the issue if my understanding is correct.

**Comment by nicholas-leonard** [comment]
Your understanding is correct. If you decide to implement it, let me know if I can be of help :)
