### ISSUE TITLE
Transfer Learning - how to "fix" weights in certain modules

### ISSUE THREAD

**Issue by jrbtaylor** [nicholas-leonard/dp#188]
I'm working on an application where a CNN feeds into an RNN and am attempting to use an ImageNet pre-trained CNN. Is there a way to fix the weights in just that one module so they're not updated during training?

**Comment by nicholas-leonard** [comment]
@jrbtaylor Yes. Just overload the accGradParameters call : 
```lua
module = loadMyImageNetModel()
module.accGradParameters = function(self) end
```
