### ISSUE TITLE
doc/neuralnetworktutorial.md  Loading the saved Experiment - needs extra line:  require 'optim'

### ISSUE THREAD

**Issue by george-colin** [nicholas-leonard/dp#189]
In:           doc/neuralnetworktutorial.md 
section:   Loading the saved Experiment

on starting a new session with 'th' and entering:
require 'dp'
xp = torch.load("/home/george/save/d2:1456235877:1.dat")
I get:
/home/george/torch/install/share/lua/5.1/torch/File.lua:334: unknown Torch class <optim.ConfusionMatrix>
stack traceback:
	[C]: in function 'error'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:334: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:344: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:344: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:344: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:344: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:344: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:360: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:344: in function 'readObject'
	/home/george/torch/install/share/lua/5.1/torch/File.lua:391: in function 'load'
	[string "xp = torch.load("/home/george/save/d2:1456235..."]:1: in main chunk
	[C]: in function 'xpcall'
	/home/george/torch/install/share/lua/5.1/trepl/init.lua:669: in function 'repl'
	...orge/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	

if instead I do:
require 'dp'
require 'optim'
xp = torch.load("/home/george/save/d2:1456235877:1.dat")
then it runs ok.

Am I right to say that you should add the extra line:
require 'optim' to your example?

(I'm just starting to use Torch, and I am having problems reloading other nnet examples as well, but this seemed the simplest example (and the only one I have got to work) so I thought I would ask about it first)

Thankyou,
George

**Comment by nicholas-leonard** [comment]
@george-colin Yes you are right. I just update the doc. Thank you.
