### ISSUE TITLE
Remember in the case of LSTM

### ISSUE THREAD

**Issue by ThorJonsson** [nicholas-leonard/dp#190]
Hi,

Thank you very much for this awesome library. Just a quick question:

In the case of lstm networks shouldn't remember be set to 'both' in line 188 of examples/recurrentlanguagemodel.lua?

Sorry if this is a stupid question, is the remember/forget functionality e.g. such that you can prevent the rnn models from having the vanishing gradient problem when dealing with long term dependencies and therefore you should not call forget when using lstms?

Regards,

Thor

**Comment by ThorJonsson** [comment]
Also, if I can add another question related to this example.

Why is it necessary do call ``lm = nn.Sequential()`` multiple times? Wouldn't it be sufficient (or more elegant) to just declare it in the beginning?

**Comment by nicholas-leonard** [comment]
@ThorJonsson It is set to `neither` for bidirectional RNNs. An alternative would be to set the forward rnn of the BRNN to remember `both` and set the backward rnn of the BRNN to remember `neither`.

**Comment by nicholas-leonard** [comment]
@ThorJonsson We call sequential multiple times when a sequential encapsulated another one : https://github.com/nicholas-leonard/dp/blob/master/examples/recurrentlanguagemodel.lua#L189

**Comment by ThorJonsson** [comment]
Brilliant, thanks a lot.
