### ISSUE TITLE
Save Experiment without EarlyStopping

### ISSUE THREAD

**Issue by Supersak80** [nicholas-leonard/dp#196]
Hi all,
I would like to save an experiment (model, etc.) to disk after running it for the maximum number of epochs without the early stopping feature. How can I modify the convolutional neural network example to do this?

Thanks,
Sam

**Comment by eywalker** [comment]
At the end of your script (i.e. after `xp:run(ds)` completes), you can simply save the experiment object itself with

```lua
torch.save('/path/to/file', xp)
```

where `xp` is the experiment object. The early stopping feature is ultimately performing the same operation.
