### ISSUE TITLE
invalid argument --normalInit   in FaceKeypoint Detector

### ISSUE THREAD

**Issue by hitesh3011** [nicholas-leonard/dp#199]
ENTERED COMMAND :
th examples/facialkeypointdetector.lua --learningRate 0.1 --maxOutNorm 2 --cuda --useDevice 1 --batchSize 16 --channelSize '{96,96}' --kernelSize '{7,7}' --poolSize '{2,2}' --poolStride '{2,2}' --hiddenSize 3000 --maxEpoch 1000 --maxTries 100 --accUpdate --normalInit --activation ReLU --submissionFile cnn1.csv

ERROR :
invalid argument: --normalInit 

Please Help!

**Comment by nicholas-leonard** [comment]
--hiddenSize '{3000}'
