### ISSUE TITLE
issue in dp.classview:32

### ISSUE THREAD

**Issue by s0min** [nicholas-leonard/dp#203]
Don't know if I missed something, but shouldn't it be 

if view ~= 'bt' **and** view ~= 'tb' then

instead of

if view ~= 'bt' **or** view ~= 'tb' then

On line 32 of classView? We only want the error to throw iff form is neither 'bt' or 'tb', currently you get error messages like 'cannot convert view "bt" to bt'.

Thanks

**Comment by nicholas-leonard** [comment]
@s0min fixed in https://github.com/nicholas-leonard/dp/commit/8f4c3a3b3bcd5e483f11034591b19cd8bc514668 .
