### ISSUE TITLE
loading one batch at a time

### ISSUE THREAD

**Issue by ethanabrooks** [nicholas-leonard/dp#204]
@nicholas-leonard thanks so much for your recent help with nn.Recurrent! The fantastic tools you have provided for RNNs have basically converted me from Theano to Torch.

I am working with a very large dataset and I would like to avoid loading the entire dataset into memory. I have actually already split the batches into different directories a la

```
train/
    batch1/
    batch2/
    ...
test/
   batch1/
   ...
```

Is there a way to load each batch one at a time in `dp.Experiment`? Thanks.

**Comment by nicholas-leonard** [comment]
@lobachevzky Appreciate the feedback :) There isn't currently a way to do this. I would suggest you build your own [DataLoader](https://github.com/Element-Research/dataload#dl.DataLoader) to do this. You can can build a loader that loads one batch from disk at a time. And wrap your loader with an [AsyncIterator](https://github.com/Element-Research/dataload#dl.AsyncIterator) to make it asynchronous and multi-threaded (i.e. faster for I/O bound loaders). But dataload doesn't work dp, so you would need to choose either or. What model are you building? What does your dataset look like?

**Comment by ethanabrooks** [comment]
The model is sequence to sequence. Currently each batch directory contains an `input.npy` and a `target.npy` file. I believe there is a library, [npy4th](https://github.com/htwaijry/npy4th) for loading these. So if I use DataLoader I can't use the dp library?

**Comment by nicholas-leonard** [comment]
@lobachevzky Yeah its one or the other. I have moved away from dp in the last months as working without it provides more flexibility. Here is an example using dataload instead of dp : https://github.com/Element-Research/rnn/blob/master/examples/recurrent-language-model.lua

**Comment by ethanabrooks** [comment]
That is super helpful. Thanks for the tip. I start to learn my way around that library.
