### ISSUE TITLE
make dp package

### ISSUE THREAD

**Issue by jeanne-wang** [nicholas-leonard/dp#209]
Hi, 

When I was git cloning the dp  package, I met with the following issues, it seems that I cannot access the repository. 

"Cloning into 'dp'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by nicholas-leonard** [comment]
clone with https instead of git, or add ssh keys to your github account.
