### ISSUE TITLE
Feature Request: OpenCL Support

### ISSUE THREAD

**Issue by ghost** [nicholas-leonard/dp#210]
This code appears to have lots of explicit calls to `:cuda()`, which rules out using it with `torch-cl` as far as I'm currently aware?

As OpenCL is getting generally much better support in ML lately, and particularly in Caffe and Torch7, it'd be nice to see this key torch library getting OpenCL support, also.

I'm aware that there's an upstreaming angle here, too; it would be nice if Torch7 presented a common GPU interface that papered over the difference between `cuda` and `opencl` tensors, so library maintainers didn't have to handle both.

Thanks!

**Comment by nicholas-leonard** [comment]
I don't support dp anymore. Most of the other packages are adding support to opencl though.

**Comment by ghost** [comment]
That's a shame! Is there any active supported fork of dp out there, or are ther other packages that supercede dp's functionality?

**Comment by nicholas-leonard** [comment]
torch-net is another fully-fledged deep learning package built over torch/nn. But personally, I recommend just using dataload + nn (+ any other package you see fit).
